
kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:18
    environment:
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm ci
  - name: wait
    image: postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: test-password
    commands:
      # wait for postgres service to become available
      - until psql -c "SELECT 1;" >/dev/null 2>&1; do sleep 1; done
  - name: database setup
    image: postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: test-password
    commands:
      - psql -c 'CREATE DATABASE "asl-test"'
      - psql -c 'CREATE DATABASE "taskflow-test"'
  - name: test
    image: node:18
    environment:
      ASL_DATABASE_HOST: postgres
      ASL_DATABASE_NAME: asl-test
      ASL_DATABASE_USERNAME: postgres
      ASL_DATABASE_PASSWORD: test-password
      DATABASE_HOST: postgres
      DATABASE_NAME: taskflow-test
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: test-password
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - npm test
  - name: audit
    image: node:18
    environment:
    commands:
      - npm run test:audit
  - name: docker build
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_BUILDKIT: 1
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
    commands:
      - docker build --secret id=github_token,env=GITHUB_AUTH_TOKEN --secret id=token,env=ART_AUTH_TOKEN -t asl-workflow .
  - name: scan-image
    pull: Always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: asl-workflow
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    when:
      event:
        - pull_request
        - push
  - name: docker push
    image: docker:dind
    environment:
      DOCKER_HOST: tcp://docker:2375
      ART_AUTH_TOKEN:
        from_secret: art_auth_token
      GITHUB_AUTH_TOKEN:
        from_secret: github_token
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-workflow quay.io/ukhomeofficedigital/asl-workflow:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-workflow:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
  - name: update manifest
    image: quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
    commands:
      - update
        --repo ukhomeoffice/asl-deployments
        --token $${GITHUB_ACCESS_TOKEN}
        --file versions.yml
        --service asl-workflow
        --version $${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test-password
